# Generated by Django 5.0.4 on 2024-05-04 18:48

import django.db.models.deletion
import home.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=home.models.GeneratingImagePath(),
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("discription", models.TextField()),
                ("points", models.IntegerField(default=0)),
                ("complated_tasks_count", models.IntegerField(default=0)),
                ("notcomplated_tasks_count", models.IntegerField(default=0)),
                (
                    "manager",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_house",
                        to="users.profile",
                    ),
                ),
            ],
        ),
    ]
