# Generated by Django 5.0.4 on 2024-05-08 18:41

import Task.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0001_initial"),
        ("home", "0001_initial"),
        ("users", "0002_profile_house"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                (
                    "data",
                    models.FileField(upload_to=Task.models.GenerateAttachmentPath()),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="Task.task",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("completed_on", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=120)),
                ("discription", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_COMPLETE", "not completed"),
                            ("COMPLETE", "complete"),
                        ],
                        default="NC",
                        max_length=12,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks_list",
                        to="users.profile",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lists",
                        to="home.house",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="tasl_list",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="Task.tasklist",
            ),
            preserve_default=False,
        ),
    ]
