# Generated by Django 5.0.4 on 2024-05-08 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Task", "0002_attachment_tasklist_task_tasl_list"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="tasl_list",
            new_name="task_list",
        ),
    ]
